baseURL = 'https://mateimicu.github.io/tw/'
languageCode = 'en-us'
title = 'TW'
theme = 'hugo-theme-learn'

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  editURL = "https://github.com/mateimicu/tw/tree/main/content/"
  author = "Micu Matei-Marius"
  description = "TW"
  showVisitedLinks = true
  disableSearch = false
  disableBreadcrumb = false
  themeVariant = "blue"
  disableLandingPageButton = true

